/*
 * Copyright 2026 Sharon Aicler (saichler@gmail.com)
 *
 * Licensed under the Apache License, Version 2.0
 */
package genlessons

import (
	"fmt"

	"github.com/saichler/l8common/go/common"
	"github.com/saichler/l8learn/go/learn/adaptive/engine"
	"github.com/saichler/l8learn/go/types/learn"
	"github.com/saichler/l8types/go/ifs"
)

var lessonFeedback *engine.LessonFeedback

// InitLessonFeedback wires the feedback loop to the GenLesson service
func InitLessonFeedback(vnic ifs.IVNic, llmClient engine.LLMClient, updater *engine.ProfileUpdater) {
	lessonFeedback = engine.NewLessonFeedback(vnic, llmClient, updater)
}

func newGenLessonServiceCallback(vnic ifs.IVNic) ifs.IServiceCallback {
	return common.NewValidation(&learn.GeneratedLesson{}, vnic).
		Require(func(v interface{}) string { return v.(*learn.GeneratedLesson).GeneratedLessonId }, "GeneratedLessonId").
		Require(func(v interface{}) string { return v.(*learn.GeneratedLesson).StudentId }, "StudentId").
		After(onGenLessonChange).
		Build()
}

func onGenLessonChange(elem interface{}, action ifs.Action, notify bool, vnic ifs.IVNic) (interface{}, bool, error) {
	lesson := elem.(*learn.GeneratedLesson)

	if action == ifs.POST {
		// Lesson generated by AI — content safety is validated before POST
		fmt.Printf("[GenLesson] New lesson generated: %s for student %s\n",
			lesson.GeneratedLessonId, lesson.StudentId)
	}

	if action == ifs.PUT {
		switch lesson.Status {
		case learn.GeneratedLessonStatus_GENERATED_LESSON_STATUS_IN_PROGRESS:
			fmt.Printf("[GenLesson] Lesson %s started by student %s\n",
				lesson.GeneratedLessonId, lesson.StudentId)

		case learn.GeneratedLessonStatus_GENERATED_LESSON_STATUS_COMPLETED:
			fmt.Printf("[GenLesson] Lesson %s completed: %d/%d correct\n",
				lesson.GeneratedLessonId, lesson.QuestionsCorrect, lesson.QuestionsTotal)

			// Run the feedback loop:
			// 1. AI generates observation analyzing performance
			// 2. Profile updated with theme/approach preferences
			// 3. Content effectiveness recorded for analytics
			if lessonFeedback != nil {
				lessonFeedback.OnLessonComplete(lesson)
			}
		}
	}

	return nil, true, nil
}
