/*
 * Copyright 2026 Sharon Aicler (saichler@gmail.com)
 *
 * Licensed under the Apache License, Version 2.0
 */
package genlessons

import (
	"github.com/saichler/l8common/go/common"
	"github.com/saichler/l8learn/go/types/learn"
	"github.com/saichler/l8types/go/ifs"
)

func newGenLessonServiceCallback(vnic ifs.IVNic) ifs.IServiceCallback {
	return common.NewValidation(&learn.GeneratedLesson{}, vnic).
		Require(func(v interface{}) string { return v.(*learn.GeneratedLesson).GeneratedLessonId }, "GeneratedLessonId").
		Require(func(v interface{}) string { return v.(*learn.GeneratedLesson).StudentId }, "StudentId").
		After(onGenLessonChange).
		Build()
}

func onGenLessonChange(elem interface{}, action ifs.Action, notify bool, vnic ifs.IVNic) (interface{}, bool, error) {
	lesson := elem.(*learn.GeneratedLesson)

	if action == ifs.POST {
		// Lesson generated by AI:
		// 1. Run ContentSafety.ValidateLesson — scan for inappropriate content
		// 2. If issues found → status stays GENERATING, retry with modified prompt
		// 3. If clean → status = READY
		// 4. Update LearningPath.currentLessonId
		// 5. Log GENERATE_LESSON to PromptLog
		_ = lesson
	}

	if action == ifs.PUT {
		switch lesson.Status {
		case learn.GeneratedLessonStatus_GENERATED_LESSON_STATUS_IN_PROGRESS:
			// Student started — pre-generate next lesson in background
			// (Pre-generation buffer: always keep 2 lessons ahead)

		case learn.GeneratedLessonStatus_GENERATED_LESSON_STATUS_COMPLETED:
			// Student finished:
			// 1. Score results (questionsCorrect / questionsTotal)
			// 2. Update SkillMastery for target skills
			// 3. ProfileUpdater.OnSessionComplete
			// 4. If >= minCorrectToAdvance → assign next lesson (advance)
			// 5. If >= minCorrectToPass → same level, different content
			// 6. If < minCorrectToPass → generate scaffold lesson (easier)
			// 7. Update LearningPath
		}
	}

	return nil, true, nil
}
